// Le icone proposte per una tipologia: quelle che servono ai rifiuti, con un nome in
// italiano per cercarle. Si può sempre scrivere a mano un'altra icona `mdi:`.
import type { Opzione } from "./selettore";

const CATALOGO: [string, string][] = [
  ["mdi:food-apple", "Mela · umido"],
  ["mdi:food-apple-outline", "Mela, contorno"],
  ["mdi:food", "Cibo"],
  ["mdi:fruit-cherries", "Ciliegie"],
  ["mdi:silverware-fork-knife", "Posate"],
  ["mdi:pot-steam", "Pentola"],
  ["mdi:coffee", "Caffè"],
  ["mdi:newspaper-variant", "Giornale · carta"],
  ["mdi:newspaper", "Giornale"],
  ["mdi:package-variant", "Scatola · cartone"],
  ["mdi:package-variant-closed", "Scatola chiusa"],
  ["mdi:bottle-soda", "Bottiglia · plastica"],
  ["mdi:bottle-soda-classic", "Bottiglia classica"],
  ["mdi:bottle-wine", "Bottiglia di vino · vetro"],
  ["mdi:glass-fragile", "Bicchiere · vetro"],
  ["mdi:glass-wine", "Calice"],
  ["mdi:glass-mug-variant", "Boccale"],
  ["mdi:trash-can", "Bidone · secco"],
  ["mdi:trash-can-outline", "Bidone, contorno"],
  ["mdi:delete-variant", "Cestino"],
  ["mdi:recycle", "Riciclo"],
  ["mdi:recycle-variant", "Riciclo, variante"],
  ["mdi:leaf", "Foglia · verde"],
  ["mdi:tree", "Albero · potature"],
  ["mdi:grass", "Erba · sfalci"],
  ["mdi:flower", "Fiore"],
  ["mdi:baby-carriage", "Passeggino · pannolini"],
  ["mdi:human-baby-changing-table", "Fasciatoio"],
  ["mdi:sofa", "Divano · ingombranti"],
  ["mdi:bed", "Letto"],
  ["mdi:fridge", "Frigorifero · RAEE"],
  ["mdi:washing-machine", "Lavatrice"],
  ["mdi:television", "Televisore"],
  ["mdi:laptop", "Computer"],
  ["mdi:cellphone", "Telefono"],
  ["mdi:lightbulb", "Lampadina"],
  ["mdi:battery", "Pile"],
  ["mdi:pill", "Farmaci"],
  ["mdi:tshirt-crew", "Abiti"],
  ["mdi:shoe-sneaker", "Scarpe"],
  ["mdi:oil", "Olio"],
  ["mdi:bucket", "Secchio"],
  ["mdi:spray-bottle", "Detersivi"],
  ["mdi:car-tire-alert", "Pneumatici"],
  ["mdi:paw", "Animali"],
  ["mdi:cup", "Bicchiere di carta"],
];

export const OPZIONI_ICONE: Opzione[] = CATALOGO.map(([id, nome]) => ({
  id,
  nome,
  dettaglio: id,
  icona: id,
}));
